version: "3.9"
name: scraper_stack

services:
  postgres:
    image: postgres:15
    container_name: scraper_postgres
    restart: always
    environment:
      POSTGRES_USER: abhay
      POSTGRES_PASSWORD: abhay123
      POSTGRES_DB: scraperdb
    ports:
      - "5433:5432"  
    volumes:
      - ~/Documents/Learn/Test/postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - scraper_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U abhay -d scraperdb"]
      interval: 5s
      retries: 5
      start_period: 5s

  metabase:
    image: metabase/metabase:latest
    container_name: scraper_metabase
    restart: always
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: postgres  # service name from docker-compose
      MB_DB_PORT: 5432      # container port, NOT host port 5433
      MB_DB_DBNAME: scraperdb 
      MB_DB_USER: abhay
      MB_DB_PASS: abhay123
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - scraper_network

networks:
  scraper_network:
    name: scraper_network
