version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_queue
    restart: always
    environment:
      POSTGRES_USER: abhay
      POSTGRES_PASSWORD: abhay123
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    # Option 1: Mount your own folder for persistence
    volumes:
      - ~/Desktop/Personal/Learning/queue/data/postgres_data:/var/lib/postgresql/data

    # Option 2: Let Docker manage the storage volume
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test
    ports:
      - "5050:80"
    depends_on:
      - postgres
    # This link is optional now â€” Compose creates a shared network automatically
    links:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
